(function (d, script) {
    script = d.createElement('script');
    script.type = 'text/javascript';
    script.async = true;
    script.onload = function () {
        head.load('http://<?php echo $this->host; ?>/css/gallery.css');
        head.js('http://ajax.googleapis.com/ajax/libs/mootools/1.1.1/mootools-yui-compressed.js', 'http://<?php echo $this->host; ?>/js/jdGallery.js', function () {
			
			divGallery = document.createElement('div');
			divGallery.id = 'myGallery';
			
			<?php 
			foreach ($this->images as $image):
			?>
			
			divImageElement = document.createElement('div');
			divImageElement.className = 'imageElement';
			
			titleImageElement = document.createElement('h3');
			titleImageElement.textContent = '<?php echo $image->getTitle() ?>';
			
			descriptionImageElement = document.createElement('p');
			descriptionImageElement.textContent = '<?php echo $image->getDescription() ?>';
			
			linkImageElement = document.createElement('a');
			linkImageElement.setAttribute('href', '<?php echo $image->getHref() ?>');
			linkImageElement.setAttribute('title', 'open image');
			linkImageElement.setAttribute('class', 'open');
			
			fullImageElement = document.createElement('img');
			fullImageElement.setAttribute('src', 'http://<?php echo $this->host; ?>/img/sites/<?php echo $this->domain ?>/<?php echo $image->getFile() ?>');
			fullImageElement.setAttribute('class', 'full');
			
			thumbImageElement = document.createElement('img');
			thumbImageElement.setAttribute('src', 'http://<?php echo $this->host; ?>/img/sites/<?php echo $this->domain ?>/<?php echo $image->getThumbnail() ?>');
			thumbImageElement.setAttribute('class', 'thumbnail');
			
			
			divImageElement.appendChild(titleImageElement);
			divImageElement.appendChild(descriptionImageElement);
			divImageElement.appendChild(linkImageElement);
			divImageElement.appendChild(fullImageElement);
			divImageElement.appendChild(thumbImageElement);
			
			
			divGallery.appendChild(divImageElement);
			
			<?php 
			endforeach;
			?>
			
			container = document.getElementById('<?php echo $this->container; ?>').appendChild(divGallery);
			
			var asd = new gallery($('myGallery'), {
                    timed: <?php echo $this->galleryConfigs['timed'] ?>,
                    delay: <?php echo $this->galleryConfigs['delay'] ?>,
                    showCarousel: <?php echo $this->galleryConfigs['showCarrousel'] ?>,
                    textShowCarousel: '<?php echo $this->galleryConfigs['textShowCarrousel'] ?>',
                    showInfopane: <?php echo $this->galleryConfigs['showInfoPane'] ?>
                });
			
        });
    };
    script.src = 'http://cdnjs.cloudflare.com/ajax/libs/headjs/0.99/head.min.js';
    d.getElementsByTagName('head')[0].appendChild(script);
}(document));