<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sDigitec CDN%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('Where enabling widgets on your site is a breeze.')) ?></p>
    <p><a class="btn btn-success btn-lg" href="#"><?php echo $this->translate('More Info') ?> &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Exisiting Customers') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('Use the following form to login') ?></p>
                <!-- 
                <form class="form-group">
                  <table width="100%" border="0" cellspacing="1" cellpadding="3">
                    <tr>
                      <td align="right"><?php echo $this->translate('Username') ?></td>
                      <td><input name="logUserName" type="text" class="form-control" id="logUserName" /></td>
                    </tr>
                    <tr>
                      <td align="right"><?php echo $this->translate('Password') ?></td>
                      <td><input name="logPassword" type="password" class="form-control" id="logPassword" /></td>
                    </tr>
                  </table>
                  <p>
                  <input type="submit" name="button" id="button" value="Login &raquo;" class="btn btn-success pull-right" />
                  </p>
                </form>
                 -->
                 <?php 
                 $form->setAttribute('action', $this->url('application', array('action' => 'login')));
                 $form->prepare();
                 echo $this->form()->openTag($form);
                 echo $this->formCollection($form);
                 echo $this->form()->closeTag();
                 ?>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Discover Modules') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('The community is working on developing a community site to serve as a repository and gallery for ZF2 modules. The project is available %son GitHub%s. The site is currently live and currently contains a list of some of the modules already available for ZF2.'), '<a href="https://github.com/zendframework/modules.zendframework.com">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank"><?php echo $this->translate('Explore ZF2 Modules') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Help &amp; Support') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('If you need any help or support while developing with ZF2, you may reach us via IRC: %s#zftalk on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the %smailing lists%s.'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?php echo $this->translate('Ping us on IRC') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
